// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	dao "server/app/dao"

	mock "github.com/stretchr/testify/mock"
)

// ContactAPI is an autogenerated mock type for the ContactAPI type
type ContactAPI struct {
	mock.Mock
}

// GetContacts provides a mock function with given fields:
func (_m *ContactAPI) GetContacts() ([]dao.Contact, error) {
	ret := _m.Called()

	var r0 []dao.Contact
	if rf, ok := ret.Get(0).(func() []dao.Contact); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dao.Contact)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
